# Generated by Django 4.1.3 on 2023-02-15 02:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0005_address_zip'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customer',
            old_name='phome',
            new_name='phone',
        ),
    ]
